# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          DigitHole
paginate:       5
baseurl:        ""
url:            "https://sihaozi61.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Curio
  url:          https://sihaozi61.github.io
  email:        sihaozi61@163.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
